#!/bin/bash
set -e

echo "==========================================="
echo "  Traefik Dev Environment - Setup Script"
echo "==========================================="

# Install docker-compose v2 if not present
if ! docker compose version &>/dev/null; then
  echo "Installing docker-compose plugin..."
  DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
  mkdir -p $DOCKER_CONFIG/cli-plugins
  curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 \
    -o $DOCKER_CONFIG/cli-plugins/docker-compose
  chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
fi

# ---------------------------------------------------------------------------
# Generate .env if it doesn't exist
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  echo ""
  echo "🔑 Generating API keys and creating .env..."

  API_KEY_API1=$(openssl rand -hex 24)
  API_KEY_API2=$(openssl rand -hex 24)
  API_KEY_WHOAMI=$(openssl rand -hex 24)

  # Build the Grafana root URL using Codespaces env vars if available
  if [ -n "$CODESPACE_NAME" ] && [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
    GRAFANA_ROOT_URL="https://${CODESPACE_NAME}-80.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/grafana"
  else
    GRAFANA_ROOT_URL="http://localhost/grafana"
  fi

  cat > .env << EOF
# =============================================================================
# Traefik Dev Environment — Environment Variables
# Auto-generated by .devcontainer/setup.sh on first Codespace launch.
# =============================================================================

# Per-service API keys
API_KEY_API1=${API_KEY_API1}
API_KEY_API2=${API_KEY_API2}
API_KEY_WHOAMI=${API_KEY_WHOAMI}

# Grafana root URL — must match the Codespaces forwarded URL for port 80
GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}

# Traefik dashboard basic auth (admin / admin123)
TRAEFIK_DASHBOARD_USER=admin
TRAEFIK_DASHBOARD_PASSWORD=admin123
EOF

  echo "   ✅ .env created"
  echo "   GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}"
else
  echo ""
  echo "   ✅ .env already exists"
  # Update GRAFANA_ROOT_URL in case the Codespace URL changed
  if [ -n "$CODESPACE_NAME" ] && [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
    GRAFANA_ROOT_URL="https://${CODESPACE_NAME}-80.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/grafana"
    if grep -q "GRAFANA_ROOT_URL" .env; then
      sed -i "s|GRAFANA_ROOT_URL=.*|GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}|" .env
    else
      echo "GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}" >> .env
    fi
    echo "   Updated GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}"
  fi
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "👉 Start all services:"
echo "   docker compose up -d --build"
echo "   (or: make up)"
echo ""
echo "👉 Then open:"
echo "   Traefik Dashboard → port 8080 Codespaces URL + /dashboard/"
echo "   Portainer         → port 9000 Codespaces URL"
echo "   Grafana           → port 80 Codespaces URL + /grafana/"
echo ""
