#!/bin/bash
set -e

echo "==========================================="
echo "  Traefik Dev Environment - Setup Script"
echo "==========================================="

# Install docker-compose v2 if not present
if ! docker compose version &>/dev/null; then
  echo "Installing docker-compose plugin..."
  DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
  mkdir -p $DOCKER_CONFIG/cli-plugins
  curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 \
    -o $DOCKER_CONFIG/cli-plugins/docker-compose
  chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
fi

# ---------------------------------------------------------------------------
# Generate .env if it doesn't exist
# This file is gitignored so it must be created on first Codespace launch.
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  echo ""
  echo "🔑 Generating API keys and creating .env..."

  API_KEY_API1=$(openssl rand -hex 24)
  API_KEY_API2=$(openssl rand -hex 24)
  API_KEY_WHOAMI=$(openssl rand -hex 24)

  cat > .env << EOF
# =============================================================================
# Traefik Dev Environment — Environment Variables
# Auto-generated by .devcontainer/setup.sh on first Codespace launch.
# Regenerate keys anytime with: openssl rand -hex 24
# =============================================================================

# Per-service API keys — each service requires its own key in X-Api-Key header
API_KEY_API1=${API_KEY_API1}
API_KEY_API2=${API_KEY_API2}
API_KEY_WHOAMI=${API_KEY_WHOAMI}

# Traefik dashboard basic auth (admin / admin123)
TRAEFIK_DASHBOARD_USER=admin
TRAEFIK_DASHBOARD_PASSWORD=admin123
EOF

  echo "   ✅ .env created with fresh API keys"
  echo ""
  echo "   API keys:"
  echo "     api1   (Products) : ${API_KEY_API1}"
  echo "     api2   (Users)    : ${API_KEY_API2}"
  echo "     whoami            : ${API_KEY_WHOAMI}"
else
  echo ""
  echo "   ✅ .env already exists — skipping key generation"
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "👉 Start all services:"
echo "   docker compose up -d --build"
echo "   (or: make up)"
echo ""
echo "👉 Then open:"
echo "   Traefik Dashboard → http://localhost:8080/dashboard/"
echo "   Web App           → http://localhost/web"
echo "   Portainer         → http://localhost/portainer/"
echo "   Grafana           → http://localhost/grafana/  (admin/admin)"
echo ""
echo "👉 Show API keys anytime:"
echo "   make show-keys"
echo ""
